spring.application.name=community

# Cassandra Local Configuration
spring.cassandra.contact-points=127.0.0.1
spring.cassandra.port=9042
spring.cassandra.keyspace-name=community_keyspace
spring.cassandra.local-datacenter=datacenter1
spring.cassandra.schema-action=create_if_not_exists

# OpenAPI Documentation
documentation.application.description=Community Microservice API
documentation.application.version=1.0.0

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operations-sorter=alpha
springdoc.swagger-ui.tags-sorter=alpha