spring:
  application:
    name: COMMUNITY_SERVICE
  cassandra:
    contact-points: 127.0.0.1
    port: 9042
    keyspace-name: community_keyspace
    local-datacenter: datacenter1
    schema-action: create_if_not_exists

# Server Configuration
server:
  port: 8086

# JWT Configuration
jwt:
  secret: d3ee61e796a04895924719559f19a19de2e31d4c330208d8c410c2d63c89de9b5aadc298404a843d521569e812c599bda47b65d4c7fce5a8ded21f24d8df59dc
  expiration: 86400000

# OpenAPI Documentation
documentation:
  application:
    description: Community Microservice API
    version: 1.0.0

# SpringDoc OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: alpha
    tags-sorter: alpha


eureka:
  client:
    service-url:
      defaultZone: ${SERVICE_DISCOVERY_URL}
  instance:
    prefer-ip-address: true